"use client";

import { useState } from "react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, BarChart, Bar } from "recharts";

export type Scenario = { frequencyMHz: number; material: string; thicknessM: number; distanceM: number; fsplDb: number; receivedDbm: number; materialLossDb: number | null };

export function ResultsPanel({ scenario }: { scenario: Scenario }) {
  const distances = [1, 5, 10, 25, 50, 100].map(distanceM => ({ distanceM, fsplDb: 32.44 + 20 * Math.log10(distanceM / 1000) + 20 * Math.log10(scenario.frequencyMHz) }));
  const wavelengths = [850, 1900, 2100, 3500, 28000].map(frequencyMHz => ({ frequencyMHz, wavelengthM: 299792458 / (frequencyMHz * 1e6) }));
  return <section className="results-area"><div className="result-cards">
    <Result label="Frecuencia" value={`${scenario.frequencyMHz.toLocaleString()} MHz`} />
    <Result label="Longitud de onda" value={`${(299792458 / (scenario.frequencyMHz * 1e6)).toFixed(3)} m`} />
    <Result label="Pérdida espacio libre" value={`${scenario.fsplDb.toFixed(2)} dB`} />
    <Result label="Atenuación material" value={scenario.materialLossDb === null ? "Pendiente de validación" : `${scenario.materialLossDb.toFixed(2)} dB`} muted={scenario.materialLossDb === null} />
    <Result label="Potencia recibida estimada" value={`${scenario.receivedDbm.toFixed(2)} dBm`} />
  </div><div className="chart-grid"><Chart title="Distancia frente a FSPL"><LineChart data={distances}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="distanceM" unit=" m"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="fsplDb" name="FSPL (dB)" stroke="#2563eb"/></LineChart></Chart><Chart title="Frecuencia frente a longitud de onda"><LineChart data={wavelengths}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="frequencyMHz" unit=" MHz"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="wavelengthM" name="λ (m)" stroke="#16a34a"/></LineChart></Chart></div><Chart title="Comparación de materiales"><BarChart data={[{ name: "Materiales validados", value: 0 }]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Legend/><Bar dataKey="value" name="Pérdida (dB)" fill="#94a3b8"/></BarChart><p className="chart-note">No se muestran comparaciones de materiales: faltan coeficientes compatibles y respaldados por fuentes técnicas.</p></Chart></section>;
}
function Result({ label, value, muted }: { label: string; value: string; muted?: boolean }) { return <article className={`result-card ${muted ? "muted" : ""}`}><span>{label}</span><strong>{value}</strong></article> }
function Chart({ title, children }: { title: string; children: React.ReactNode }) { return <div className="chart-card"><h3>{title}</h3><ResponsiveContainer width="100%" height={240}><>{children}</></ResponsiveContainer></div> }

export function Fundamentals() { const items = [["Onda electromagnética", "Una perturbación que transporta energía mediante campos eléctricos y magnéticos."], ["Frecuencia", "Número de ciclos por segundo, expresado en hertz (Hz)."], ["Longitud de onda", "Distancia entre crestas consecutivas: λ = c / f."], ["FSPL", "Pérdida ideal que ocurre al propagarse una señal en espacio libre."], ["Atenuación", "Reducción de potencia causada por distancia, obstáculos o medios."], ["Decibelio y dBm", "El dB expresa una relación; el dBm expresa potencia respecto a 1 mW."], ["Jaula de Faraday", "Recinto conductor que puede reducir campos electromagnéticos según su geometría y frecuencia."], ["Interferencia vs atenuación", "La interferencia activa añade señales no deseadas; la atenuación pasiva reduce energía al atravesar un medio."]]; return <section className="education"><p className="kicker">APRENDIZAJE</p><h2>Fundamentos de telecomunicaciones</h2><div className="fundamentals-grid">{items.map(([title, text])=><div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section> }

export function ScenarioComparator({ current }: { current: Scenario }) { const [saved, setSaved] = useState<Scenario | null>(null); return <section className="comparator"><div><p className="kicker">ANÁLISIS COMPARATIVO</p><h2>Comparador de escenarios</h2><p>Guarda una configuración para revisar diferencias sin persistencia externa.</p></div><div className="compare-actions"><button className="secondary" onClick={() => setSaved(current)}>Guardar como escenario A</button>{saved && <button className="secondary" onClick={() => setSaved(null)}>Limpiar A</button>}</div>{saved ? <div className="compare-table"><div></div><strong>Escenario A</strong><strong>Actual B</strong>{[["Frecuencia", `${saved.frequencyMHz} MHz`, `${current.frequencyMHz} MHz`],["Material", saved.material, current.material],["Grosor", `${saved.thicknessM} m`, `${current.thicknessM} m`],["Distancia", `${saved.distanceM} m`, `${current.distanceM} m`],["FSPL", `${saved.fsplDb.toFixed(2)} dB`, `${current.fsplDb.toFixed(2)} dB`],["Potencia RX", `${saved.receivedDbm.toFixed(2)} dBm`, `${current.receivedDbm.toFixed(2)} dBm`]].map(([label,a,b])=><><span key={`${label}-l`}>{label}</span><span key={`${label}-a`}>{a}</span><span key={`${label}-b`}>{b}</span></>)}</div> : <div className="empty-compare">Aún no hay un escenario guardado.</div>}</section> }
